#!/usr/bin/env python3
"""Route-by-route SEO report from the raw built HTML (Prompt 16).
Writes docs/playbook/16-seo-report.md. Run after build.py and check.py."""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from check import ORIGIN, PageParser, url_of  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
dist = ROOT / "dist"
sitemap = (dist / "sitemap.xml").read_text()
rows = []
for f in sorted(dist.rglob("*.html")):
    url = url_of(f, dist)
    raw = f.read_text()
    p = PageParser()
    p.feed(raw)
    noindex = 'name="robots" content="noindex' in raw
    types = []
    for block in p.jsonld:
        types = [g["@type"] for g in json.loads(block)["@graph"]]
    checks = {
        "title": bool(p.title.strip()),
        "desc": 110 <= len(p.meta.get("description", "")) <= 170,
        "canonical": noindex or p.canonical == ORIGIN + url,
        "h1": p.h1 == 1,
        "og": all(p.meta.get(k) for k in ("og:title", "og:description", "og:url", "og:image"))
        and p.meta["og:image"].startswith("https://"),
        "jsonld": len(p.jsonld) == 1,
        "sitemap": (f"<loc>{ORIGIN}{url}</loc>" in sitemap) != noindex,
    }
    status = "PASS" if all(checks.values()) else "FAIL: " + ", ".join(k for k, v in checks.items() if not v)
    rows.append((url, len(p.title), len(p.meta.get("description", "")), "noindex" if noindex else "index",
                 ", ".join(t for t in types if t not in ("Organization",)), status))

out = [
    "# Prompt 16: Server-rendered SEO report",
    "",
    "Generated by scripts/seo_report.py from the raw built HTML in dist/ (no JavaScript executed).",
    "Every page is a static file, so what is listed here is exactly what crawlers receive.",
    "",
    "Site-wide: robots.txt allows all and points to sitemap.xml; /thank-you/ is disallowed and noindex;",
    "404.html is noindex and served with a 404 status by Netlify; canonicals use https://houstonpowerwashingpro.com;",
    "Open Graph and Twitter images are absolute URLs; one JSON-LD @graph per page (no duplicates).",
    "",
    "| Route | Title chars | Description chars | Indexing | JSON-LD types (plus Organization) | Result |",
    "|---|---|---|---|---|---|",
]
out += [f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} |" for r in rows]
passed = sum(1 for r in rows if r[5] == "PASS")
out += ["", f"{passed} of {len(rows)} routes pass."]
(ROOT / "docs" / "playbook" / "16-seo-report.md").write_text("\n".join(out) + "\n")
print(f"{passed}/{len(rows)} routes pass")
